### ISSUE TITLE
Teach Travis how it can use Django

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/vgbrowser#21]
Currently, Travis is not happy with our Django setup:
![image](https://user-images.githubusercontent.com/10184961/61935473-e2fba100-af8a-11e9-87a6-139f1ed2e873.png)

As I have the same issue on my local machine, maybe @josiahseaman could help me resolve this?
Thanks ;)

**Comment by josiahseaman** [comment]
Good news!  I figured it out.  It was a matter of dependencies.
I found watching the [Travis page](https://travis-ci.org/graph-genome/vgbrowser) very helpful.

715b0cf661fc2f53d06e895b8ec71f411247f23f
0e04a2332d85b2788f26e365387388eed7733a1e
968522f9a936e68d7f58aaf748880722a9419a47
