### ISSUE TITLE
Interface of GFA should support our decorated GFA format.

### ISSUE THREAD

**Issue by 6br** [graph-genome/vgbrowser#29]
Because our decorated GFA format should not include sequence anymore, we need to allow to remove sequence in GFA format. I will fix the import/export of GFA format in our browser.

**Comment by ekg** [comment]
We can set the sequence to be `*`.

**Comment by 6br** [comment]
> Outputs a stack of summarizations of the base graph, with nodes in each level above the bottom (input graph) annotated with the node ids in the previous layer that they are summarizing

Also, we need to extend node tags to be included the previous layer's node ids.

**Comment by josiahseaman** [comment]
I have noticed you can do this by preserving the node name as long as node
name is not restricted to be a dense id.  If node id and name are different
you can get creative in naming.

Josiah Seaman
Bioinformatics and Genome Visualization
Royal Botanic Gardens Kew
+44 775805 6670

**Comment by ekg** [comment]
Node names in vg-GFA are restricted to be integers, ideally dense ones.

We might need to write a converter though.

**Comment by 6br** [comment]
## Decorated GFA - As Data Exchange Format

### Header field:
Header field should include a layer number as follows.

TAG	TYPE	EXAMPLE	DESCRIPTION
LA	i	LA:i:1		The layer number.


### Segment fields:
Segment fields exactly have an optional field. I assume that the segment fields should have a reference to the high level nodes.

TAG	TYPE	EXAMPLE	DESCRIPTION
LN	i	LN:i:1024	Segment length (is used on summarized layer.)
HI	i	HI:i:12		A reference to the higher layer nodes.
HI	B	HI:B:i4,5,6	References to the higher layer nodes.
LO	B	LO:B:i1,2,3	References to the lower layer nodes.
SB	B	SB:B:i8	References to the sibling (i.e. repricated in the summarized layer) nodes.

### Link fields:
Link fields are the same as the original GFA.

### Path fields:
Path field needs to be represented the sort order, reference to the original path (because path names might need to be unique across all layers).
Path lines are not specified to have optional tags in GFA specification, though this information should be stored in path lines themselves.

TAG	TYPE	EXAMPLE	DESCRIPTION
	ID	i	ID:i:2		The sort order.
	RF	i	RF:Z:chr1	Reference to the original path name.

**Comment by josiahseaman** [comment]
Looking at the file format: [GFA Format](http://gfa-spec.github.io/GFA-spec/GFA1.html)
Containment line might allow us to encode summarization links.  Summary nodes contain multiple nodes inside of them.  It's at least worth thinking about:

-------------------------------  
## C Containment line
A containment line represents an overlap between two segments where one (the Contained segment) is contained in the other (the Container segment). The Pos field stores the leftmost position of the contained segment in the container segment in its forward orientation (i.e. before this is oriented according to the ContainerOrient sign).

## Example
The following line describes the containment of segment 2 in the reverse complement of segment 1, starting at position 110 of segment 1 (in its forward orientation).
`C  1 - 2 + 110 100M`

**Comment by 6br** [comment]
Okay, I will re-think, and I need to confirm whether VG supports Containment line currently.

**Comment by josiahseaman** [comment]
I just wanted to mention the option.  But if we go with Matrix Visualization it will be irrelevant anyways.😥

**Comment by 6br** [comment]
Yes, but however, I am wondering the concept of summarization layers can be usable for any other purpose.

**Comment by josiahseaman** [comment]
I think we should close this issue until we decide we're actually going to use something that could be called Graph Summarization.  So far, ODGI bin seems to solve the same problem more simply.
